# Generated by Django 5.1.6 on 2025-03-06 03:04

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='share_link',
            field=models.CharField(default=api.models.generate_unique_link, editable=False, max_length=200, unique=True),
        ),
    ]
