# Generated by Django 5.1.6 on 2025-03-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_file_share_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='downloads',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
